version: 2

builds:
  - main: .
    binary: planc
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

release:
  mode: replace
  replace_existing_artifacts: true
  header: |
    ## Release Notes

    {{ readFile "CHANGELOG.md" }}
  extra_files:
    - glob: CHANGELOG.md

brews:
  - repository:
      owner: jakebf
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/jakebf/planc
    description: A tiny TUI for browsing Claude Code plans
    license: MIT
    install: |
      bin.install "planc"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
